# Generated by Django 2.2.7 on 2019-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191205_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moduledetails',
            name='quantity2',
            field=models.IntegerField(default=0),
        ),
    ]
