# Generated by Django 2.2.6 on 2019-12-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_componentdetails_tender_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledetails',
            name='board_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='moduledetails',
            name='board_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
