# Generated by Django 2.2.6 on 2019-12-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_moduledetails_board_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdetails',
            name='board_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='componentdetails',
            name='board_desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
