# Generated by Django 2.2.6 on 2019-12-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191225_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentdetails',
            old_name='description',
            new_name='component_desc',
        ),
        migrations.AddField(
            model_name='componentdetails',
            name='module_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='componentdetails',
            name='module_desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
