# Generated by Django 2.2.7 on 2019-12-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_moduledetails_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='total_quantity',
            field=models.FloatField(default=0),
        ),
    ]
