# Generated by Django 2.2.6 on 2019-12-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191225_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduledetails',
            old_name='description',
            new_name='module_desc',
        ),
    ]
