# Generated by Django 2.2.7 on 2019-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191205_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='total_quantity',
            field=models.FloatField(),
        ),
    ]
