# Generated by Django 2.2.6 on 2019-12-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191225_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentdetails',
            old_name='quantity',
            new_name='component_quantity',
        ),
    ]
