# Generated by Django 2.2.6 on 2019-12-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191225_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='bus_section',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='moduledetails',
            name='type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('bus_coupler', 'Bus Coupler'), ('outgoing', 'Outgoing')], default='', max_length=20),
        ),
    ]
