# Generated by Django 2.2.7 on 2019-12-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191205_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarddetails',
            name='no_of_bus_section',
        ),
    ]
