# Generated by Django 2.2.6 on 2019-12-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191226_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='bus_section',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
