# Generated by Django 2.2.7 on 2019-12-09 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191209_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentdetails',
            name='module_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.ModuleDetails'),
        ),
    ]
