# Generated by Django 2.2.6 on 2019-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191226_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('bus_coupler', 'Bus Coupler'), ('outgoing', 'Outgoing')], default='incoming', max_length=15),
        ),
    ]
