# Generated by Django 2.2.6 on 2019-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191227_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledetails',
            name='type',
        ),
        migrations.AlterField(
            model_name='moduledetails',
            name='module_type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('bus_coupler', 'Bus Coupler'), ('outgoing', 'Outgoing')], default='incoming', max_length=15),
        ),
    ]
