# Generated by Django 2.2.6 on 2019-12-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191227_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='bus_section',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
