# Generated by Django 2.2.6 on 2019-12-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191227_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='module_type',
            field=models.CharField(help_text='Select one:incoming/bus_coupler/outgoing', max_length=20),
        ),
    ]
