# Generated by Django 2.2.6 on 2019-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191227_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='bus_section',
            field=models.CharField(blank=True, help_text='Enter number from 1 to 5.', max_length=6),
        ),
    ]
