# Generated by Django 2.2.6 on 2019-12-28 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191227_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdatadetails',
            name='tender_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 15, 2, 21, 390938)),
        ),
    ]
