# Generated by Django 2.2.6 on 2019-12-31 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191228_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddetails',
            name='phase',
            field=models.CharField(help_text='Select one : D / T / N', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenderdatadetails',
            name='tender_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 15, 25, 12, 926384, tzinfo=utc)),
        ),
    ]
