# Generated by Django 2.2.6 on 2019-12-31 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191231_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddetails',
            name='indoor_or_outdoor',
            field=models.CharField(help_text='Select one : indoor / outdoor', max_length=30),
        ),
        migrations.AlterField(
            model_name='boarddetails',
            name='stand_or_non',
            field=models.CharField(help_text='Select one : standard / nonstandard', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenderdatadetails',
            name='tender_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 15, 29, 36, 411207, tzinfo=utc)),
        ),
    ]
