# Generated by Django 2.2.6 on 2019-12-31 17:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191231_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boards',
            old_name='BRD_CODE',
            new_name='board_code',
        ),
        migrations.RenameField(
            model_name='boards',
            old_name='BRD_DESC',
            new_name='board_desc',
        ),
        migrations.AlterField(
            model_name='tenderdatadetails',
            name='tender_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 17, 42, 35, 689593, tzinfo=utc)),
        ),
    ]
