# Generated by Django 3.0.2 on 2020-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200130_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpreport',
            name='business_line',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
