# Generated by Django 3.0.2 on 2020-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dumpreport_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpreport',
            name='table_type',
            field=models.CharField(choices=[('insert', 'Insert'), ('replace', 'Replace')], default='', max_length=10),
        ),
    ]
