# Generated by Django 2.2.9 on 2020-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200203_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpreport',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default=True, max_length=10),
        ),
    ]
