# Generated by Django 2.2.9 on 2020-02-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_mrnreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrnreport',
            old_name='invoice_nO',
            new_name='invoice_no',
        ),
    ]
