# Generated by Django 2.2.9 on 2020-02-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200211_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrnreport',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='', max_length=10),
        ),
    ]
