# Generated by Django 2.2.9 on 2020-02-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_mrnreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnreport',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10),
        ),
    ]
