# Generated by Django 2.2.9 on 2020-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200212_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnreport',
            name='from_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mrnreport',
            name='to_date',
            field=models.CharField(max_length=50),
        ),
    ]
