# Generated by Django 2.2.9 on 2020-02-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200212_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRNReportGSTNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=50)),
                ('to_date', models.CharField(max_length=50)),
            ],
        ),
    ]
