# Generated by Django 2.2.9 on 2020-02-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_mrnreportgstnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnreportgstnew',
            name='from_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mrnreportgstnew',
            name='to_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
