# Generated by Django 2.2.9 on 2020-02-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200219_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('from_date', models.CharField(blank=True, max_length=100)),
                ('to_date', models.CharField(blank=True, max_length=100)),
                ('_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
