# Generated by Django 2.2.9 on 2020-02-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_contributionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionreport',
            name='table_type',
            field=models.CharField(choices=[('create&insert', 'Create & Insert'), ('create_table', 'Create'), ('insert', 'Insert'), ('replace', 'Replace')], default='', max_length=20),
        ),
    ]
