# Generated by Django 2.2.9 on 2020-02-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_contributionreport_ladger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributionreport',
            old_name='ladger',
            new_name='ladger_id',
        ),
    ]
