# Generated by Django 2.2.9 on 2020-02-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200225_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionreport',
            name='_id',
        ),
    ]
