# Generated by Django 2.2.9 on 2020-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_contributionreport__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionreport',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='', max_length=10),
        ),
    ]
