# Generated by Django 2.2.3 on 2020-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200225_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_contribution_report', 'Trip to Mussoorie'), ('view_mrn_report', 'Trip to Haridwaar')),
            },
        ),
    ]
