# Generated by Django 2.2.3 on 2020-05-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedgerPassbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_number', models.CharField(blank=True, max_length=100)),
                ('customer_site', models.CharField(blank=True, max_length=100)),
                ('customer_type', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
