# Generated by Django 2.2.3 on 2020-06-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_customerledgerpassbook_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerledgerpassbook',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
