# Generated by Django 2.2.3 on 2020-06-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20200610_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=300)),
                ('value', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='customerledgerpassbook',
            name='attribute',
            field=models.ManyToManyField(to='app.Attribute'),
        ),
    ]
