# Generated by Django 2.2.3 on 2020-06-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200611_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledgerpassbook',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
