# Generated by Django 2.2.3 on 2020-06-19 07:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0042_auto_20200619_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserForm',
        ),
    ]
