# Generated by Django 2.2.3 on 2020-06-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200619_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='User',
            new_name='user',
        ),
    ]
