# Generated by Django 2.2.3 on 2020-06-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200619_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='branch',
            field=models.TextField(),
        ),
    ]
