# Generated by Django 2.2.3 on 2020-06-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20200619_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledgerpassbook',
            name='customer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customerledgerpassbook',
            name='customer_site',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customerledgerpassbook',
            name='customer_type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customerledgerpassbook',
            name='organisation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
