# Generated by Django 2.2.7 on 2019-12-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191214_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddetails',
            name='board_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
