# Generated by Django 2.2.7 on 2019-12-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUSBAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BB_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('BB_PRIC', models.CharField(blank=True, max_length=50, null=True)),
                ('BB_OLD', models.CharField(blank=True, max_length=50, null=True)),
                ('BS_PRIC', models.CharField(blank=True, max_length=50, null=True)),
                ('BPVC_PRIC', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLAS_DAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MODU_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('NO_OF_CLAS', models.IntegerField(blank=True, null=True)),
                ('CLASS1', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS2', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS3', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS4', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS5', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS6', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS7', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS8', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS9', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS10', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS11', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CLASS12', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CNONSIZE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('WIDTH', models.FloatField(blank=True, null=True)),
                ('CLASS1', models.FloatField(blank=True, max_length=50, null=True)),
                ('CLASS2', models.FloatField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMP_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CONM', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_RAT', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CLAS', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CLAS1', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CLAS2', models.CharField(blank=True, max_length=50, null=True)),
                ('OLD_PRIC', models.CharField(blank=True, max_length=50, null=True)),
                ('NEW_PRIC', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_PRIC', models.CharField(blank=True, max_length=50, null=True)),
                ('CURR_JUN06', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_DESC', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_PRNT', models.CharField(blank=True, max_length=50, null=True)),
                ('JUN06', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
