# Generated by Django 2.2.7 on 2019-12-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_busbar_clas_dat_cnonsize_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_dat',
            name='CLASS9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
