# Generated by Django 2.2.7 on 2019-12-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191218_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMPCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMP_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CONM', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('DISC', models.CharField(blank=True, max_length=50, null=True)),
                ('EXCS', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COMPDIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMP_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CONM', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_DESC', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_PRIC', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_DIS', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COMPMAST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MODU_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('QTY', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DOTMOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DMOD_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('DOTDESC', models.CharField(blank=True, max_length=50, null=True)),
                ('DOTCST', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GLAND',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GLAND_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('GLAND_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('GLAND_DESC', models.CharField(blank=True, max_length=50, null=True)),
                ('GLAND_RATE', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LUG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LUG_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('LUG_RATE', models.CharField(blank=True, max_length=50, null=True)),
                ('LUG_DESC', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LUGLNDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GLAND_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('NO_CORES', models.FloatField(blank=True, null=True)),
                ('LUG_CODE', models.FloatField(blank=True, null=True)),
                ('GLAND_CODE', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MAKE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('NO_OPTIONS', models.FloatField(blank=True, null=True)),
                ('NO_OF_CHAR', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MODCOMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMOD_CD', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_QTY', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MODU_RTG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCH_MCODE', models.CharField(blank=True, max_length=50, null=True)),
                ('MOD_RTG', models.CharField(blank=True, max_length=50, null=True)),
                ('MOD_RTGCO', models.CharField(blank=True, max_length=50, null=True)),
                ('UNITS', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MODU_SIZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMOD_CD', models.CharField(blank=True, max_length=50, null=True)),
                ('SIZE_FIX', models.CharField(blank=True, max_length=50, null=True)),
                ('SIZE_DT', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MODUNAME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOD_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('MOD_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('FCH_MCODE', models.CharField(blank=True, max_length=50, null=True)),
                ('TOT_RTGS', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PN_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_DESC', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_DPTH', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_HT', models.CharField(blank=True, max_length=50, null=True)),
                ('PPCK_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('PHRC_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('PCRC_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('PBF_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('PEPX_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_SHUT', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_SHRD', models.CharField(blank=True, max_length=50, null=True)),
                ('LABOUR', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RATDES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCH_MCODE', models.CharField(blank=True, max_length=50, null=True)),
                ('CLASS', models.IntegerField(blank=True, null=True)),
                ('DESRIP', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROWPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POS_NO', models.IntegerField(blank=True, null=True)),
                ('SCRE_P', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEQUENCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NBS', models.IntegerField(blank=True, null=True)),
                ('NBC', models.IntegerField(blank=True, null=True)),
                ('FBC_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('SBC_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('NIC', models.IntegerField(blank=True, null=True)),
                ('IC_TYPEM', models.CharField(blank=True, max_length=50, null=True)),
                ('IC_TYPEP', models.CharField(blank=True, max_length=50, null=True)),
                ('SEQUENCE', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDER_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('CUSTOMER', models.CharField(blank=True, max_length=50, null=True)),
                ('PROJECT', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_SHET', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_BF', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_EPNT', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_GLCMP', models.CharField(blank=True, max_length=50, null=True)),
                ('BB_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('PVC_SLEV', models.CharField(blank=True, max_length=50, null=True)),
                ('PROC_FLAG', models.CharField(blank=True, max_length=50, null=True)),
                ('HTS_BOLT', models.CharField(blank=True, max_length=50, null=True)),
                ('SHRO_UDS', models.CharField(blank=True, max_length=50, null=True)),
                ('NA_USER', models.CharField(blank=True, max_length=50, null=True)),
                ('COMNO', models.CharField(blank=True, max_length=50, null=True)),
                ('ORUSE_FLAG', models.CharField(blank=True, max_length=50, null=True)),
                ('CHK_DIR', models.CharField(blank=True, max_length=50, null=True)),
                ('BACK_UP_FL', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WMOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WMOD_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('WDESC', models.CharField(blank=True, max_length=50, null=True)),
                ('WBCST', models.FloatField(blank=True, null=True)),
                ('WCCST', models.FloatField(blank=True, null=True)),
                ('WLABOUR', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cnonsize',
            name='CLASS1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cnonsize',
            name='CLASS2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
