# Generated by Django 2.2.7 on 2019-12-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191218_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CNONSIZE',
        ),
    ]
