# Generated by Django 2.2.7 on 2019-12-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_cnonsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNONSIZE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('WIDTH', models.FloatField(blank=True, null=True)),
                ('HEIGHT', models.FloatField(blank=True, null=True)),
                ('DEPTH', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
