# Generated by Django 2.2.7 on 2019-12-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_comp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MAKE',
        ),
    ]
