# Generated by Django 2.2.7 on 2019-12-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='NAME',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
