# Generated by Django 2.2.7 on 2019-12-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_comp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
