# Generated by Django 2.2.7 on 2019-12-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20191220_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentdetails',
            name='board_detail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
