# Generated by Django 2.2.7 on 2019-12-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191214_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderdatadetails',
            name='slug_field',
        ),
    ]
