# Generated by Django 2.2.7 on 2019-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191217_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOARDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRD_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('BRD_DESC', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY', models.CharField(blank=True, max_length=50, null=True)),
                ('BRD_STN', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY_MCC', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY_VBCC', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY_PCC', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY_PDUM', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY_PRL8', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY_PRL4', models.CharField(blank=True, max_length=50, null=True)),
                ('BQTY_DUM', models.CharField(blank=True, max_length=50, null=True)),
                ('BCMP_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BDOT_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BCGL_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BPGL_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BPFB_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BMFB_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BLFB_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BWRG_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BLWRG_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BBB_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BCBB_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BSPC_CST', models.CharField(blank=True, max_length=50, null=True)),
                ('BUNP', models.CharField(blank=True, max_length=50, null=True)),
                ('BFRG', models.CharField(blank=True, max_length=50, null=True)),
                ('BMLPF', models.CharField(blank=True, max_length=50, null=True)),
                ('BERTC', models.CharField(blank=True, max_length=50, null=True)),
                ('BTOTAL', models.CharField(blank=True, max_length=50, null=True)),
                ('BHBB_RTNG', models.CharField(blank=True, max_length=50, null=True)),
                ('BRD_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_PHS', models.CharField(blank=True, max_length=50, null=True)),
                ('PN_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('BCBB_QTY', models.CharField(blank=True, max_length=50, null=True)),
                ('FRO_ACCS', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
