# Generated by Django 2.2.7 on 2019-12-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191218_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cnonsize',
            old_name='CLASS1',
            new_name='DEPTH',
        ),
        migrations.RenameField(
            model_name='cnonsize',
            old_name='CLASS2',
            new_name='HEIGHT',
        ),
    ]
