# Generated by Django 2.2.7 on 2019-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_make'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAKE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('COMP_CODE', models.CharField(blank=True, max_length=50, null=True)),
                ('NO_OPTIONS', models.FloatField(blank=True, null=True)),
                ('NO_OF_CHAR', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
