# Generated by Django 2.2.7 on 2019-12-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20191218_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardsTableData',
        ),
        migrations.DeleteModel(
            name='ComponentsAll',
        ),
        migrations.DeleteModel(
            name='ModuleAll',
        ),
        migrations.DeleteModel(
            name='ModulesMix',
        ),
    ]
