# Generated by Django 2.2.7 on 2019-12-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20191218_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COMP',
        ),
    ]
