# Generated by Django 2.2.7 on 2019-12-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20191218_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentdetails',
            name='module_detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
