# Generated by Django 2.2.7 on 2019-12-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20191220_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentdetails',
            old_name='module_detail',
            new_name='board_detail',
        ),
    ]
