# Generated by Django 3.0.2 on 2020-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200131_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpreport',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dumpreport',
            name='sales_account',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dumpreport',
            name='shipping_org',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dumpreport',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
