# Generated by Django 3.0.2 on 2020-01-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200131_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpreport',
            name='table_type',
            field=models.CharField(choices=[('insert', 'Insert'), ('replace', 'Replace')], default=False, max_length=10),
        ),
    ]
