# Generated by Django 2.2.9 on 2020-02-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dumpreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpreport',
            name='report_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10),
        ),
    ]
