# Generated by Django 2.2.7 on 2019-12-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191211_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddetails',
            name='board_desc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
