# Generated by Django 2.2.7 on 2019-12-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191211_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddetails',
            name='board_desc',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.BoardsTableData'),
        ),
    ]
