# Generated by Django 2.2.7 on 2019-12-14 05:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191211_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdatadetails',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='tender_code'),
        ),
    ]
