# Generated by Django 2.2.7 on 2019-12-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tenderdatadetails_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenderdatadetails',
            old_name='slug',
            new_name='slug_field',
        ),
    ]
