# Generated by Django 2.2.7 on 2019-12-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cnonsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COMP',
        ),
    ]
