# Generated by Django 2.2.7 on 2019-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMP_CODE', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_CONM', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_RAT', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_CLAS', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_CLAS1', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_CLAS2', models.CharField(blank=True, max_length=100, null=True)),
                ('OLD_PRIC', models.CharField(blank=True, max_length=100, null=True)),
                ('NEW_PRIC', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_PRIC', models.CharField(blank=True, max_length=100, null=True)),
                ('CURR_JUN06', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_DESC', models.CharField(blank=True, max_length=100, null=True)),
                ('COMP_PRNT', models.CharField(blank=True, max_length=100, null=True)),
                ('JUN06', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
