# Generated by Django 2.2.3 on 2020-07-29 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200728_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='application_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_application_id', to='app.APPLICATION'),
        ),
    ]
