# Generated by Django 2.2.3 on 2020-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200729_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_end_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_end_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
