# Generated by Django 2.2.3 on 2020-08-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_approval_hierarchy_task_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_approvals',
            name='approval_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
