# Generated by Django 2.2.3 on 2020-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_task_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_resources',
            name='resource_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Manager'), ('Co-ordinator', 'Co-ordinator'), ('team', 'Team'), ('dba', 'DBA')], max_length=100),
        ),
    ]
