# Generated by Django 2.2.3 on 2020-08-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_task_approvals_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_approvals',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
