# Generated by Django 2.2.7 on 2019-12-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentdetails',
            name='module_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
