# Generated by Django 2.2.7 on 2019-12-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191223_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdetails',
            name='module_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ModuleDetails'),
        ),
        migrations.AlterField(
            model_name='componentdetails',
            name='board_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BoardDetails'),
        ),
    ]
