# Generated by Django 2.0.2 on 2019-10-23 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_code', models.CharField(max_length=100)),
                ('board_desc', models.CharField(max_length=100)),
                ('board_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_or_non', models.CharField(choices=[('standard', 'STANDARD'), ('nonstandard', 'NONSTANDARD')], default='', max_length=100)),
                ('indoor_or_outdoor', models.CharField(choices=[('indoor', 'INDOOR'), ('outdoor', 'OUTDOOOR')], default='', max_length=100)),
                ('mcc_or_nonstan', models.CharField(choices=[('mcc code', 'MCC CODE'), ('non_stan code', 'NON_STAN CODE')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TenderProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(max_length=250, unique=True)),
                ('project_name', models.CharField(max_length=250, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('panel_sheet', models.CharField(choices=[('hrc', 'HRC'), ('crc', 'CRC')], max_length=3)),
                ('epoxy_paint', models.BooleanField(default=False)),
                ('base_frame', models.BooleanField(default=False)),
                ('gland_comp', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=7)),
                ('bus_bar', models.CharField(choices=[('alum.', 'Alum.'), ('copper', 'Copper')], max_length=7)),
                ('pvc_sleeves', models.BooleanField(default=False)),
                ('htc_bolt', models.BooleanField(default=False)),
                ('shutter_mcc', models.BooleanField(default=False)),
                ('shrouds', models.BooleanField(default=False)),
                ('board_code', models.CharField(default='cs_101', max_length=100)),
                ('stand_or_non', models.CharField(choices=[('standard', 'STANDARD'), ('nonstandard', 'NONSTANDARD')], default='', max_length=100)),
                ('indoor_or_outdoor', models.CharField(choices=[('indoor', 'INDOOR'), ('outdoor', 'OUTDOOOR')], default='', max_length=100)),
                ('mcc_or_nonstan', models.CharField(choices=[('mcc code', 'MCC CODE'), ('non_stan code', 'NON_STAN CODE')], default='', max_length=100)),
                ('board_desc', models.CharField(default='desc_1001', max_length=100)),
                ('board_qty', models.IntegerField(default=0)),
                ('mcc_description', models.CharField(blank=True, max_length=100)),
                ('hori_bus_bar_desc', models.CharField(blank=True, help_text='Amps', max_length=100)),
                ('control_bus_bar_qty', models.IntegerField(default=0)),
                ('front_access_panel', models.BooleanField(default=True)),
                ('phase', models.CharField(choices=[('D', 'D'), ('T', 'T'), ('N', 'N')], default='', help_text='D=DP/T=TP/N=TPN', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.AddField(
            model_name='addboard',
            name='board_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BoardType'),
        ),
    ]
