# Generated by Django 2.0.2 on 2019-10-23 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addboard',
            name='board_type',
        ),
        migrations.DeleteModel(
            name='AddBoard',
        ),
        migrations.DeleteModel(
            name='BoardType',
        ),
    ]
