# Generated by Django 2.2.3 on 2020-03-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorManagementForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('person_to_meet', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
