# Generated by Django 2.2.3 on 2020-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyVistior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('mobile_number', models.CharField(max_length=12)),
                ('Approved_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyVistiorFormFilled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=200)),
                ('host_department', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=150)),
                ('visitor_valid_upto', models.CharField(max_length=100)),
                ('Approved_by', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorManagementForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=12)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('person_to_meet', models.CharField(blank=True, max_length=400)),
                ('v_date_time', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('pic', models.ImageField(default='images/a.jpg', upload_to='images/')),
            ],
        ),
    ]
