# Generated by Django 2.2.3 on 2020-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyvistiorformfilled',
            name='host_name',
            field=models.CharField(max_length=100),
        ),
    ]
