# Generated by Django 2.2.3 on 2020-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200410_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=200)),
                ('host_department', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('visitor_valid_upto', models.CharField(max_length=100)),
            ],
        ),
    ]
