# Generated by Django 2.2.3 on 2020-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200330_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('person_to_meet', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
