# Generated by Django 2.2.3 on 2020-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vmsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormanagementform',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
