# Generated by Django 2.2.3 on 2020-04-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_frequentvisitors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequencyVistiorFormFilled',
        ),
    ]
