# Generated by Django 2.2.3 on 2020-03-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_visitormanagementform_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormanagementform',
            name='reason',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
