# Generated by Django 2.2.3 on 2020-04-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_frequencyvistiorformfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileregistered',
            name='mobile_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
