# Generated by Django 2.2.3 on 2020-03-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_visitormanagementform_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitormanagementform',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
