# Generated by Django 2.2.3 on 2020-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200410_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentvisitors',
            name='approved_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frequentvisitors',
            name='pic',
            field=models.ImageField(default='images/a.jpg', upload_to='images/'),
        ),
    ]
