# Generated by Django 2.2.3 on 2020-04-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200410_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentvisitors',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
