# Generated by Django 2.2.3 on 2020-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200331_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitormanagementform',
            name='is_approved',
            field=models.BooleanField(),
        ),
    ]
