# Generated by Django 2.2.3 on 2020-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200401_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitormanagementform',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
