# Generated by Django 2.2.3 on 2020-04-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_frequentvisitors_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentvisitors',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='frequentvisitors',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
