# Generated by Django 2.2.3 on 2020-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200401_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormanagementform',
            name='v_date_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
