# Generated by Django 2.2.3 on 2020-04-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200411_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentvisitors',
            name='visitor_registration_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
