# Generated by Django 2.2.3 on 2020-04-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mobileregistered_f_visitor_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentvisitors',
            name='mobile_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='mobileregistered',
            name='mobile_number',
            field=models.CharField(max_length=12),
        ),
    ]
