# Generated by Django 2.2.3 on 2020-04-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200411_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyvistior',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='frequentvisitors',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='mobileregistered',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visitormanagementform',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
