# Generated by Django 2.2.3 on 2020-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200411_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormanagementform',
            name='Approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
