# Generated by Django 2.2.3 on 2020-04-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_visitormanagementform_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormanagementform',
            name='approve_by_security',
            field=models.CharField(blank=True, choices=[('approve', 'Approve')], max_length=9),
        ),
    ]
