# Generated by Django 2.2.3 on 2020-04-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_visitormanagementform_approve_by_security'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequencyVistior',
        ),
    ]
