# Generated by Django 2.2.3 on 2020-04-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_frequencyvistior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentvisitors',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
