# Generated by Django 2.2.3 on 2020-04-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200415_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequentvisitors',
            name='pic',
            field=models.ImageField(default='images/a.jpg', upload_to='images/'),
        ),
    ]
