# Generated by Django 2.2.3 on 2020-04-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200416_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitormanagementform',
            options={'permissions': (('assign_task', 'Assign task'),)},
        ),
    ]
