# Generated by Django 2.2.3 on 2020-04-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200422_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_security_form', 'View the Security Form'), ('view_host_form', 'View the Host Form')),
            },
        ),
    ]
