# Generated by Django 2.2.3 on 2020-04-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_visitormanagementform_visitor_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentvisitors',
            name='visitor_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
