# Generated by Django 2.2.3 on 2020-05-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apextable',
            name='process',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
