# Generated by Django 2.2.3 on 2020-05-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apextable_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apextable',
            name='process',
        ),
        migrations.AddField(
            model_name='apextable',
            name='apex_process',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apextable',
            name='mail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
