# Generated by Django 2.2.3 on 2020-05-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200513_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apextable',
            name='apex_process',
        ),
        migrations.AddField(
            model_name='apextable',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
