# Generated by Django 2.2.3 on 2020-05-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200513_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apextable',
            old_name='is_approved',
            new_name='apex_status',
        ),
    ]
