# Generated by Django 2.2.3 on 2020-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200513_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='apextable',
            name='apex_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apextable',
            name='sys_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='apextable',
            name='sys_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
