# Generated by Django 2.2.3 on 2020-06-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200601_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apextable',
            old_name='apex_json',
            new_name='item_code',
        ),
        migrations.AddField(
            model_name='apextable',
            name='email',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
