# Generated by Django 2.2.3 on 2020-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200601_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apextable',
            name='item_code',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
