# Generated by Django 2.2.3 on 2020-06-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200601_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apextable',
            old_name='mail',
            new_name='mail_status',
        ),
    ]
