# Generated by Django 2.2.3 on 2020-06-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200601_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='apextable',
            name='initiative_email',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
