# Generated by Django 2.2.3 on 2020-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_apextable_initiative_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apextable',
            name='initiative_email',
        ),
        migrations.AddField(
            model_name='apextable',
            name='initiator_email',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
