# Generated by Django 3.0.2 on 2020-01-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_line', models.CharField(max_length=100)),
                ('business_unit', models.CharField(max_length=100)),
                ('shipping_org', models.CharField(max_length=100)),
                ('unit', models.CharField(default='', max_length=100)),
                ('sales_account', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
