# Generated by Django 3.0.2 on 2020-01-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_erpreport_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpreport',
            name='data',
        ),
    ]
