# Generated by Django 3.0.2 on 2020-01-24 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200124_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpreport',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
