# Generated by Django 2.2.3 on 2020-08-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200807_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='login_crete_user',
            new_name='login_create_user',
        ),
    ]
