# Generated by Django 2.2.3 on 2020-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200809_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='can_create_application',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='can_create_project',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
