# Generated by Django 2.2.3 on 2020-08-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200809_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_flag',
            field=models.CharField(blank=True, choices=[('na', 'NA'), ('on_going', 'On Going'), ('complete', 'Complete')], max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('change', 'Change')], max_length=50),
        ),
    ]
