# Generated by Django 2.2.3 on 2020-08-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200827_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
