# Generated by Django 2.2.3 on 2020-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200827_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('Requirement Document', ' Requirement Document'), ('Technical Design', 'Technical Design'), ('Functional Design', 'Functional Design'), (' Test Script', ' Test Script')], max_length=100),
        ),
    ]
