# Generated by Django 2.2.3 on 2020-08-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_people_can_create_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_approvals',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
