# Generated by Django 2.2.3 on 2020-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200829_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='approval_flag',
            field=models.CharField(blank=True, choices=[('Not Required', 'Not Required'), ('on_going', 'On Going'), ('complete', 'Complete')], max_length=50),
        ),
    ]
