# Generated by Django 2.2.3 on 2020-09-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_task_initial_expected_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_approvals',
            name='forwarded_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
