# Generated by Django 2.2.3 on 2020-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_task_approvals_forwarded_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task_creation',
            field=models.CharField(blank=True, choices=[('self', 'Anyone can create the task'), ('owner', 'Only owner can create the task')], max_length=100),
        ),
    ]
