# Generated by Django 2.2.3 on 2020-09-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20200904_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_description',
            new_name='notification_category',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notification_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='task_id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='attribute_1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notifications',
            name='attribute_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notifications',
            name='person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_name', to='app.PEOPLE'),
        ),
    ]
