# Generated by Django 2.2.3 on 2020-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200905_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='person_name',
        ),
        migrations.AddField(
            model_name='notifications',
            name='person_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
