# Generated by Django 2.2.3 on 2020-09-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200905_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='person_id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_name', to='app.PEOPLE'),
        ),
    ]
