# Generated by Django 2.2.3 on 2020-09-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200905_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
