# Generated by Django 2.2.3 on 2020-08-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='login_crete_user',
        ),
    ]
