# Generated by Django 2.2.3 on 2020-08-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200811_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='TASK_APPROVALS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(blank=True, max_length=100)),
                ('executed', models.CharField(blank=True, max_length=100)),
                ('approval_status', models.BooleanField(blank=True, default=False)),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_by', to='app.PEOPLE')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_to', to='app.PEOPLE')),
                ('task_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_idd', to='app.TASK')),
            ],
        ),
        migrations.CreateModel(
            name='APPROVAL_HIERARCHY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy_line_id', models.CharField(blank=True, max_length=100)),
                ('approval_level', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, choices=[('parallel', 'Parallel'), ('alternate', 'Alternate')], max_length=50)),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwardd_by', to='app.PEOPLE')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwardd_to', to='app.PEOPLE')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_id', to='app.PROJECT')),
            ],
        ),
    ]
