# Generated by Django 2.2.3 on 2020-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200813_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_dbs_processing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
