# Generated by Django 2.2.3 on 2020-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initial_exp_completion_dt',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
