# Generated by Django 2.2.3 on 2020-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200829_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initial_expected_end_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
