# Generated by Django 2.1.13 on 2020-06-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FUNCTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_id', models.CharField(blank=True, max_length=100)),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('executable', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='INTERACTION_OUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('l_palette_id', models.CharField(blank=True, max_length=100)),
                ('sent_time', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PALETTE_STRUCTURE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(blank=True, max_length=100)),
                ('response_text', models.CharField(blank=True, max_length=200)),
                ('callback_p_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PALETTES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(blank=True, max_length=100)),
                ('p_name', models.CharField(blank=True, max_length=100)),
                ('p_type', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(blank=True)),
                ('p_text', models.TextField(blank=True)),
                ('input_parameter_type', models.CharField(blank=True, max_length=50)),
                ('user_auth_req', models.CharField(blank=True, max_length=100)),
                ('function_id', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SESSION_WINDOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_number', models.CharField(blank=True, max_length=12)),
                ('start_timestamp', models.CharField(blank=True, max_length=100)),
                ('updated_timestamp', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
