# Generated by Django 2.1.13 on 2020-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileLink', models.FileField(blank=True, null=True, upload_to='Documents_Folder/')),
            ],
        ),
        migrations.CreateModel(
            name='CONNECTION_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('port', models.CharField(blank=True, max_length=4)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('server', models.CharField(blank=True, max_length=100)),
                ('database_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='General_configuration_chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hour', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], max_length=2)),
                ('keyword', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='INTERACTION_IN_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(blank=True, max_length=200)),
                ('from_no', models.CharField(blank=True, max_length=200)),
                ('to_no', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('contentType', models.CharField(blank=True, max_length=200)),
                ('attachmentType', models.CharField(blank=True, max_length=200)),
                ('fileLink', models.CharField(blank=True, max_length=200)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('latitude', models.CharField(blank=True, max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PALETTE_TABLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(blank=True, max_length=100)),
                ('p_name', models.CharField(blank=True, max_length=100)),
                ('p_type', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('p_text', models.TextField(blank=True)),
                ('input_parameter_type', models.CharField(blank=True, max_length=50)),
                ('user_auth_req', models.CharField(blank=True, max_length=100)),
                ('function_id', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('encoded_data', models.TextField(blank=True)),
                ('contentType', models.CharField(blank=True, max_length=200)),
                ('attachmentType', models.CharField(blank=True, max_length=200)),
                ('fileLink', models.FileField(blank=True, null=True, upload_to='Documents_Folder/')),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('latitude', models.CharField(blank=True, max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=200)),
                ('palette_category', models.CharField(choices=[('text', 'Text'), ('location', 'Location'), ('document', 'Document'), ('image', 'Image'), ('video', 'Video')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WHATSAPP_MAIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('email_id', models.CharField(blank=True, max_length=200)),
                ('whatsapp_number', models.CharField(blank=True, max_length=12)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whatsapp_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=10)),
                ('key', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PALETTES',
        ),
        migrations.AlterModelOptions(
            name='palette_structure',
            options={'ordering': ['-p_id']},
        ),
        migrations.AddField(
            model_name='function',
            name='connection_type',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('sql', 'SQL'), ('mysql', 'MYSQL')], default='oracle', max_length=10),
        ),
    ]
