# Generated by Django 2.1.13 on 2020-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200724_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='connection_type',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('sql', 'SQL'), ('mysql', 'MYSQL')], max_length=10),
        ),
    ]
