# Generated by Django 2.1.13 on 2020-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200724_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_window',
            name='wa_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='whatsapp_mail',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
