# Generated by Django 2.1.13 on 2020-07-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200725_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_No',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
