# Generated by Django 2.2.9 on 2020-02-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200203_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpreport',
            name='table_type',
            field=models.CharField(choices=[('insert', ' Insert '), ('update', 'Update'), ('replace', 'Replace')], max_length=20),
        ),
    ]
