# Generated by Django 2.2.9 on 2020-02-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200203_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpreport',
            name='table_type',
            field=models.CharField(choices=[('create&insert', 'Create & Insert '), ('create ', 'Create'), ('insert', 'Insert'), ('replace', 'Replace')], max_length=20),
        ),
    ]
