# Generated by Django 2.2.9 on 2020-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200203_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRNReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_org', models.CharField(blank=True, max_length=100)),
                ('item_category', models.CharField(blank=True, max_length=100)),
                ('from_date', models.CharField(max_length=11)),
                ('to_date', models.CharField(max_length=11)),
                ('vender', models.CharField(blank=True, max_length=100)),
                ('po_number', models.CharField(blank=True, max_length=200)),
                ('item', models.CharField(blank=True, max_length=100)),
                ('mrn_no', models.CharField(blank=True, max_length=100)),
                ('gate_entry_no', models.CharField(blank=True, max_length=100)),
                ('invoice_nO', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
