# Generated by Django 2.2.9 on 2020-02-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_mrnreport_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnreport',
            name='table_type',
            field=models.CharField(choices=[('create&insert', 'Create & Insert'), ('create_table', 'Create'), ('insert', 'Insert'), ('replace', 'Replace')], max_length=20),
        ),
    ]
