# Generated by Django 2.2.3 on 2020-05-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_window',
            old_name='START_TIME',
            new_name='START_TIMESTAMP',
        ),
        migrations.RenameField(
            model_name='session_window',
            old_name='UPDATED_TIME',
            new_name='UPDATED_TIMESTAMP',
        ),
    ]
