# Generated by Django 2.2.3 on 2020-05-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200520_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_window',
            old_name='START_TIMESTAMP',
            new_name='start_timestamp',
        ),
        migrations.RenameField(
            model_name='session_window',
            old_name='UPDATED_TIMESTAMP',
            new_name='updated_timestamp',
        ),
        migrations.RenameField(
            model_name='session_window',
            old_name='WA_NUMBER',
            new_name='wa_number',
        ),
    ]
