# Generated by Django 2.2.3 on 2020-05-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200521_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction_out',
            name='MESSAGE_ID',
        ),
    ]
