# Generated by Django 2.2.3 on 2020-05-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200521_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palette_structure',
            old_name='CALLBACK_P_ID',
            new_name='p_id',
        ),
        migrations.RemoveField(
            model_name='palette_structure',
            name='RESPONSE_TEXT',
        ),
        migrations.AddField(
            model_name='palette_structure',
            name='callback_p_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='palette_structure',
            name='pesponse_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
