# Generated by Django 2.2.3 on 2020-05-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200521_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='palettes',
            name='p_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
