# Generated by Django 2.2.3 on 2020-05-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_palettes_p_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palette_structure',
            old_name='pesponse_text',
            new_name='response_text',
        ),
    ]
