# Generated by Django 2.2.7 on 2019-12-05 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=20, null=True)),
                ('board_code', models.CharField(max_length=100)),
                ('stand_or_non', models.CharField(choices=[('standard', 'STANDARD'), ('nonstandard', 'NONSTANDARD')], default='', max_length=100)),
                ('indoor_or_outdoor', models.CharField(choices=[('indoor', 'INDOOR'), ('outdoor', 'OUTDOOOR')], default='', max_length=100)),
                ('mcc_or_nonstan', models.CharField(max_length=100)),
                ('board_desc', models.CharField(max_length=100)),
                ('board_qty', models.IntegerField(null=True)),
                ('mcc_description', models.CharField(blank=True, max_length=100)),
                ('hori_bus_bar_desc', models.CharField(blank=True, help_text='Amps', max_length=100)),
                ('control_bus_bar_qty', models.IntegerField(default=0)),
                ('front_access_panel', models.BooleanField(default=True)),
                ('no_of_bus_section', models.IntegerField(default=0)),
                ('delete', models.BooleanField(default=False)),
                ('phase', models.CharField(choices=[('D', 'D'), ('T', 'T'), ('N', 'N')], default='', help_text='D=DP/T=TP/N=TPN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BoardsAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BodyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=20, null=True)),
                ('panel_sheet', models.CharField(choices=[('hrc', 'HRC'), ('crc', 'CRC')], max_length=3)),
                ('epoxy_paint', models.BooleanField(default=False)),
                ('shrouts', models.BooleanField(default=False)),
                ('htc_bolt', models.BooleanField(default=False)),
                ('shutter_mcc', models.BooleanField(default=False)),
                ('bus_bar', models.CharField(choices=[('alum.', 'Alum.'), ('copper', 'Copper')], max_length=7)),
                ('pvc_sleeves', models.BooleanField(default=False)),
                ('base_frame', models.BooleanField(default=False)),
                ('gland_comp', models.CharField(choices=[('single', 'Single'), ('double', 'Double')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentsAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ModulesMix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=60)),
                ('module_id', models.IntegerField()),
                ('component_id', models.CharField(max_length=30)),
                ('component_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TenderDataProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
        migrations.CreateModel(
            name='TenderDataDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_code', models.CharField(max_length=20)),
                ('tender_version', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=250)),
                ('project_name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_code', models.CharField(max_length=20)),
                ('tender_version', models.CharField(max_length=20)),
                ('board_id', models.CharField(max_length=30)),
                ('module_id', models.CharField(max_length=30)),
                ('module_code', models.CharField(default='', max_length=30)),
                ('module_type', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=60)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('quantity2', models.IntegerField(blank=True, default=0)),
                ('quantity3', models.IntegerField(blank=True, default=0)),
                ('quantity4', models.IntegerField(blank=True, default=0)),
                ('quantity5', models.IntegerField(blank=True, default=0)),
                ('type', models.CharField(choices=[('incoming', 'Incoming'), ('bus_coupler', 'Bus Coupler'), ('outgoing', 'Outgoing')], default='', max_length=20)),
                ('bus_section', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('revision', models.CharField(default='', max_length=50)),
                ('board_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BoardDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_code', models.CharField(max_length=20)),
                ('tender_version', models.CharField(max_length=20)),
                ('module_id', models.CharField(max_length=30)),
                ('component_id', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=60)),
                ('quantity', models.IntegerField(default=0)),
                ('module_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ModuleDetails')),
            ],
        ),
    ]
