# Generated by Django 2.2.7 on 2019-12-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191205_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduledetails',
            old_name='tender_code',
            new_name='tender_id',
        ),
    ]
