# Generated by Django 2.2.7 on 2019-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191205_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledetails',
            name='total_quantity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
