# Generated by Django 2.2.7 on 2019-12-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191209_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentdetails',
            name='module_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ModuleDetails'),
        ),
    ]
