# Generated by Django 3.0.2 on 2020-01-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200131_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpreport',
            name='table_type',
            field=models.CharField(choices=[('insert', 'Insert Table'), ('replace', 'Replace Table')], max_length=10),
        ),
    ]
