# Generated by Django 3.0.2 on 2020-01-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200124_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erpreport',
            name='from_data',
        ),
        migrations.AddField(
            model_name='erpreport',
            name='from_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='erpreport',
            name='to_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
