# Generated by Django 3.0.2 on 2020-01-24 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200124_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erpreport',
            name='from_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='erpreport',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
