# Generated by Django 2.2.3 on 2020-04-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_visitormanagementform_v_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VMSModel',
        ),
    ]
