# Generated by Django 2.2.3 on 2020-08-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_task_required_dbs_processing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='required_dbs_processing',
            new_name='required_dba_processing',
        ),
    ]
