# Generated by Django 2.2.3 on 2020-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200829_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_business_owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
