# Generated by Django 2.2.7 on 2019-12-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduledetails',
            name='tender_version',
        ),
    ]
