# Generated by Django 2.2.7 on 2019-12-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_moduledetails_tender_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledetails',
            name='tender_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
