# Generated by Django 2.2.3 on 2020-05-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FUNCTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_ID', models.CharField(blank=True, max_length=100)),
                ('F_NAME', models.CharField(blank=True, max_length=100)),
                ('EXECUTABLE', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='INTERACTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MESSAGE_ID', models.CharField(blank=True, max_length=100)),
                ('SESSION_ID', models.CharField(blank=True, max_length=100)),
                ('L_PALETTE_ID', models.CharField(blank=True, max_length=100)),
                ('SENT_TIME', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PALETTE_STRUCTURE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RESPONSE_TEXT', models.CharField(blank=True, max_length=100)),
                ('CALLBACK_P_ID', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PALETTES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_NAME', models.CharField(blank=True, max_length=100)),
                ('P_TYPE', models.CharField(blank=True, max_length=100)),
                ('ACTIVE', models.BooleanField(blank=True)),
                ('P_TEXT', models.CharField(blank=True, max_length=100)),
                ('USER_AUTH_REQ', models.CharField(blank=True, max_length=100)),
                ('FUNCTION_ID', models.CharField(blank=True, max_length=100)),
                ('INPUT_PAR_REQ', models.CharField(blank=True, max_length=100)),
                ('SESSION_ID', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SESSION_WINDOW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SESSION_ID', models.CharField(blank=True, max_length=100)),
                ('WA_NUMBER', models.IntegerField(blank=True)),
                ('START_TIME', models.CharField(blank=True, max_length=100)),
                ('UPDATED_TIME', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
