# Generated by Django 2.2.3 on 2020-05-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200520_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_window',
            name='SESSION_ID',
        ),
    ]
