# Generated by Django 2.2.3 on 2020-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_session_window_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_window',
            name='WA_NUMBER',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
