# Generated by Django 2.2.3 on 2020-05-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200520_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='INTERACTION',
            new_name='INTERACTION_OUT',
        ),
    ]
