# Generated by Django 2.2.3 on 2020-05-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_interaction_out_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction_out',
            old_name='L_PALETTE_ID',
            new_name='l_palette_id',
        ),
        migrations.RenameField(
            model_name='interaction_out',
            old_name='SENT_TIME',
            new_name='sent_time',
        ),
        migrations.RenameField(
            model_name='interaction_out',
            old_name='SESSION_ID',
            new_name='session_id',
        ),
    ]
