# Generated by Django 2.2.3 on 2020-05-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200521_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palettes',
            old_name='ACTIVE',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='palettes',
            old_name='FUNCTION_ID',
            new_name='function_id',
        ),
        migrations.RenameField(
            model_name='palettes',
            old_name='INPUT_PAR_REQ',
            new_name='input_par_req',
        ),
        migrations.RenameField(
            model_name='palettes',
            old_name='P_NAME',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='palettes',
            old_name='P_TEXT',
            new_name='p_text',
        ),
        migrations.RenameField(
            model_name='palettes',
            old_name='P_TYPE',
            new_name='p_type',
        ),
        migrations.RenameField(
            model_name='palettes',
            old_name='SESSION_ID',
            new_name='session_id',
        ),
        migrations.RenameField(
            model_name='palettes',
            old_name='USER_AUTH_REQ',
            new_name='user_auth_req',
        ),
    ]
