# Generated by Django 2.2.3 on 2020-05-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200521_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette_structure',
            name='input_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='palettes',
            name='input_parameter_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
