# Generated by Django 2.2.3 on 2020-05-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200526_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palettes',
            name='input_par_req',
        ),
    ]
