# Generated by Django 2.2.3 on 2020-05-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_palettes_input_par_req'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='EXECUTABLE',
            new_name='executable',
        ),
        migrations.RenameField(
            model_name='function',
            old_name='F_ID',
            new_name='f_id',
        ),
        migrations.RenameField(
            model_name='function',
            old_name='F_NAME',
            new_name='f_name',
        ),
    ]
