# Generated by Django 2.2.3 on 2020-05-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200527_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palettes',
            name='p_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
