# Generated by Django 2.2.3 on 2020-05-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200529_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palettes',
            name='p_text',
            field=models.TextField(blank=True),
        ),
    ]
